# Generated by Django 5.2.3 on 2025-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuatorstate',
            old_name='led',
            new_name='is_on',
        ),
    ]
